#=============================================================================================== 日志配置
sdklog:
  logpath: D:\Desktop\DevProject\AAAlogs

sdk:
  datasource:
    ip: localhost
    username: root
    password: root
    port: 3306
    database: bluetooth-app
